# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v2
      with:
        source_repo: "https://Geniusflip:${{ secrets.PASSWORD }}@github.com/Geniusflip/studious-umbrella.git"
        source_branch: "master"
        destination_repo: "https://Geniusflip:${{ secrets.PASSWORD }}@github.com/Geniusflip/quickblopg.git"
        destination_branch: "notes"


